### ISSUE TITLE
Node-Red

### ISSUE THREAD

**Issue by alexcclarke** [tobiasrask/wmbus-client#1]
Hello Tobias,
Was wondering if one could included your wmbus client in Node Red.  Would be really cool for IoT related data collection from the Multical 21

Br
Alex

**Comment by sunsetdk** [comment]
There is a node-red node for the multical21 out now.

node-red-contrib-wmbus-client

**Comment by KekkerFink** [comment]
I get an error when trying to install wmbus-client. Can you help?
![node red wmbus](https://user-images.githubusercontent.com/48657493/54517200-4cc2c900-4961-11e9-80aa-00503e2ea849.JPG)

**Comment by sunsetdk** [comment]
> 
> 
> I get an error when trying to install wmbus-client. Can you help?
> 

Which version of Node.JS are you using? 
I have not touched this code since i created it :)
On which platform are you trying to install the node-red component?

**Comment by KekkerFink** [comment]
Its on a Raspberry Pi 3+ and Node.JS is version v6.11.3.
By the way, will the node output the actual meter value?

**Comment by sunsetdk** [comment]
It will output the actual meter value, and any alarms.

I'n not very good with node. i can see my pi use node 10.14.2 same as my windows where i developed the plugin. I can see that there is a problem with buffer and the file you get with no file or dir found.

**Comment by KekkerFink** [comment]
I got the AES key now, but I still have not manage to install wmbus-client. Are you running it on a Raspberry Pi? Which version and setup are you sure is working?
Thank you in advance.

**Comment by tobiasrask** [comment]
I will close this one.
See https://www.npmjs.com/package/node-red-contrib-wmbus-client
