### ISSUE TITLE
AMBER WM-Bus Module AMB8465-M

### ISSUE THREAD

**Issue by Paulo7414** [tobiasrask/wmbus-client#2]
Hi,

Can you please share the user settings from the AMBER WM-Bus Module AMB8465-M that you used?
The app output is always "No meter data for: My meter (VolumeCold)"

Thank You,

Paulo Pereira

**Comment by tobiasrask** [comment]
Hi Paulo,

Sorry my late answer, I missed the notification. I will check out the Amber configuration and update the documentation.

Tobias

**Comment by tobiasrask** [comment]
Time has passed, but I will add comment also here: I added notes for README how to configure the client. There is (hard coded) values for Amber:

```
{
      baudRate: 9600,
      dataBits: 8,
      stopBits: 1,
      parity: 'none'
}
```

After this you should be able to communicate with dongle. Second this is that you should enable the raw data buffering from dongle to your computer.
