### ISSUE TITLE
iM871a-USB

### ISSUE THREAD

**Issue by valdiks** [tobiasrask/wmbus-client#3]
Hello Tobias,
Can you add iM871a-USB dongle support to the app?

Thank you.

**Comment by tobang** [comment]
That would be very much appreciated. I have this dongle too.

Thank you

**Comment by sunsetdk** [comment]
I have writte the code to make it work with the Im871a, and is trying to see if i can share the code with the world.

**Comment by sunsetdk** [comment]
I have created a branch which does support the Im871a USB dongle. I hope that Tobias will take those changes and commit them the main code. But otherwise look at the branch created.

**Comment by tobang** [comment]
Great, I'll take a look. Thank you.

**Comment by tobang** [comment]
@sunsetdk - Tried your code, and I get the following: I am running on a Raspberry PI

Start Wireless M-Bus reader...
Connection opened
(node:8245) Warning: N-API is an experimental feature and could change at any time.
unknown unknown, null -> null = 0, delta: 0 -> 0
24.11.2018,unknown,2d2c383118631b16,unknown,null,null,0,null,0,0

unknown unknown, null -> null = 0, delta: 0 -> 0
24.11.2018,unknown,2d2c323118631b16,unknown,null,null,0,null,0,0

unknown unknown, null -> null = 0, delta: 0 -> 0
24.11.2018,unknown,2d2c003118631b16,unknown,null,null,0,null,0,0

unknown unknown, null -> null = 0, delta: 0 -> 0
unknown unknown, null -> null = 0, delta: 0 -> 0
unknown unknown, null -> null = 0, delta: 0 -> 0

**Comment by sunsetdk** [comment]
I can't tell with you get an error. This is my first attempt to work with Node JS so sorry for the code quality, but I will attempt to help as much as possible.

Have you created the meters.json file with the AES key and serial number of the meter inside? This need to be created in a data folder which is as the same level as the folder with the code inside.

Is 38311863 the serial number of your meter?

René

**Comment by tobang** [comment]
Yes 38311863, and I have created a meters.json file i a data folder. In the file there are two properties I do not know where to find on the meter: 
"version": "1b",
"deviceType": "06",
Are they part of the type number on the meter?

Torben

**Comment by sunsetdk** [comment]
@tobiasrask  is sit an option that I could be made contributer of your project?

**Comment by tobiasrask** [comment]
@sunsetdk yes I would appreciate that very much. I wasn't able to test your code, but it looks good. 
I reviewed your PR. Can I ask to add unit test for the new fields?

I'm glad that you documented the cc-field and added support for the info bytes. When I started working with this project about four years ago, there was no documentation available and getting the required information was not easy.

It would be nice if we have own examples for different dongles, I can add these.

**Comment by sunsetdk** [comment]
This is my first attempt with node.js. But I'll attempt to make some units test to check the new fields.

**Comment by sunsetdk** [comment]
This is my first attempt with node.js. But I'll attempt to make some units test to check the new fields.

**Comment by sunsetdk** [comment]
I have added tests. Hope they were what you ment.

As i think you can see i have changed a few other bits, like made the dongles eventbased, but i shouldn't have made and breaking changes to the original code.

**Comment by tobiasrask** [comment]
I will close this since https://github.com/tobiasrask/wmbus-client/pull/4 is merged now.
